# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: MIT
from .fixtures import (
    host,
    host_esxcfg_vswitch_1,
    host_esxcfg_vswitch_2,
    host_esxcfg_vswitch_3,
    host_esxcfg_vmknic_1,
    host_esxcfg_vmknic_2,
    host_esxcfg_vmknic_3,
    host_esxcfg_nics_1,
    host_esxcfg_nics_2,
    host_gold_vmx,
    host_gold_vmx_ptp_old_esxi,
    host_gold_vmx_ptp_new_esxi,
    host_gold_vmx_ptp_new_esxi_hex,
    host_getallvms,
    host_api,
    host_api_with_cert,
    host_api_with_vf_info_and_interfaces,
    vcenter,
    datacenter,
    cluster,
    cluster_host,
    standalone_host,
    datastore,
    virtual_adapter,
    virtual_machine,
    dswitch,
    dsportgroup,
    dsuplink,
    vswitch,
    vsportgroup,
    vcenter_named_entities,
)
